### ISSUE TITLE
Latency on CIFAR-10 vs CIFAR-100

### ISSUE THREAD

**Issue by minhquoc0712** [RICE-EIC/HW-NAS-Bench#10]
Hi, thank you for your interesting research.

I want to ask about the latency measured on CIFAR-10 and CIFAR-100 for NAS-Bench-201. Since these two datasets have the same image resolution (32 x 32), can I assume that the difference in measured latency of the same architecture on these two datasets mainly comes from using different inputs?

**Comment by licj15** [comment]
the difference in measured latency of the same architecture on these two datasets mainly comes from using different output dimensions (i.e., 10 vs. 100)

**Comment by minhquoc0712** [comment]
Thanks, I should have noticed that.
