### ISSUE TITLE
Edge TPU latency

### ISSUE THREAD

**Issue by minhquoc0712** [RICE-EIC/HW-NAS-Bench#11]
Hi,

Why are there some architectures that have negative latency on EdgeTPU?

Thank you.

![image](https://github.com/GATECH-EIC/HW-NAS-Bench/assets/53263073/1bde8ec8-417a-44ed-a7e4-b1877f37176d)

**Comment by licj15** [comment]
Thank you for your interest in our work!

"-1" represents that the corresponding model did not pass the compilation process of Edge GPU compiler (https://coral.ai/docs/edgetpu/compiler)
