### ISSUE TITLE
About FBNet Search Space

### ISSUE THREAD

**Issue by Bowenwu1** [RICE-EIC/HW-NAS-Bench#2]
Congratulations on the acceptance of ICLR!

I'm confused about your dataset on FBNet search space.

In your paper, you mentioned that "HW-NAS-Bench provides measured/estimated hardware-cost on six hardware devices for all the 10^21 architectures of FBNet search space".

If measuring one architecture taking 0.1 seconds, then measuring all 10^21 architectures will take 10^21 * 0.1 / (60*60*24*365)=3.1709792e+12 years.
If you could estimate 10^9 architectures per second, then measuring all 10^21 architectures will take 10^12 seconds, roughly 30000 years.

So, I'm really curious about how to perform such a big estimation task across such big search space.

**Comment by licj15** [comment]
Thanks for your interest in our HW-NAS-Bench! 
Both collecting and querying the hardware-cost for all architectures in the FBNet space won't take so many years. 

1. How we collect the hardware-cost for the architectures in the FBNet space: We sum up the hardware-cost of all unique blocks (i.e., "block" in the FBNet space (Wu et al., 2019)) within all possible network architectures. The number of all the unique blocks (i.e., ~250) is much smaller than that of all the architectures (10^21) in the FBNet space, so it's practical to measure/estimate them all. 
2. How users query the hardware-cost for the architectures in the FBNet space: The hardware-cost of **all** architectures in the FBNet search space can be accessed by [our provided API](https://github.com/RICE-EIC/HW-NAS-Bench#how-to-use-hw-nas-bench).  Please note that 1) the current HW-NAS method usually won't iterate all architectures in the search space; and 2) the latency to access the hardware-cost via our provided API is much smaller than the latency of the HW-NAS algorithms. So querying the hardware-cost of architectures in the FBNet space using our provided API will cause negligible time overheads to the HW-NAS algorithms. 
You can refer to Table 2 and the corresponding description in our [current version](https://openreview.net/pdf?id=_0kaDkv3dVf) for more detailed information.
