### ISSUE TITLE
About FBNet Search Space  Measure/Estimate

### ISSUE THREAD

**Issue by yandan-sunny** [RICE-EIC/HW-NAS-Bench#3]
I'm very interested in your work.
And I'm confused about summing up the hardware-cost of all unique blocks of the architecture as its final hardware-cost. How do you deal with hardware-cost changes caused by layer to layer fusion?

**Comment by licj15** [comment]
Thank you for your interest in HW-NAS-Bench!
To verify whether we can use the "summing up the hardware-cost" to approximate the "final hardware-cost" (e.g., is there a "layer to layer fusion" issue), we analyze their correlation coefficients on different devices in Table 2 of [our paper](https://arxiv.org/pdf/2103.10584.pdf). One observations from it is that we may not be able to do this in EdgeTPU (e.g., there may be a "layer to layer fusion" issue), so we do not include EdgeTPU in FBNet search space. Notably, for the NAS-Bench-201 search space, we do not such an approximation.
