### ISSUE TITLE
without accurcy metrics?can`t I get the methrics throught the network config(string)  instead of index? 

### ISSUE THREAD

**Issue by cmlin8** [RICE-EIC/HW-NAS-Bench#5]
HW-NAS-Bench looks like not provide the accurcy metircs?
I can get the accurcy metrics in NAS-Bench-201 but I can not get the accurcy metrics in anywhere

**Comment by licj15** [comment]
Thank you for your interest in HW-NAS-Bench!
As you mentioned, because the accuracy metrics has already released NAS-Bench-201's official codebase [here](https://github.com/D-X-Y/NAS-Bench-201), we are not considering including it in our code release currently.

**Comment by akhauriyash** [comment]
Hello,

What about the FBNet accuracy metric? Could you kindly refer me to how I can fetch the accuracy of the FBNet networks? I'd really appreciate the help :)
