### ISSUE TITLE
HLS estimates generation?

### ISSUE THREAD

**Issue by dj-park** [RICE-EIC/HW-NAS-Bench#6]
Hi,
I wonder if you have plan to release the C code for Vivado HLS. Based on the paper, it seems like you have 9 blocks, and you ran C-synthesis in Vivado HLS for each block and get the latency/power estimates. Thanks in advance.

**Comment by licj15** [comment]
Thank you for your interest in HW-NAS-Bench! Currently, we don't have the plan to release the C code for Vivado HLS.
