### ISSUE TITLE
 [Question] Consistency with NATS Bench ordering

### ISSUE THREAD

**Issue by fracapuano** [RICE-EIC/HW-NAS-Bench#9]
This might sound like a stupid (yet very significant question): **is the order of the architectures the same for HW-NAS and Nats Bench (~NAS Bench 201)?**

I (quickly) inspected the repo and found no call to other projects (such as `xautodl` or `nats-bench`), hence my doubt. Just to make sure I am more than clear I am referring to the output of the following prompt: 

```python
from nats_bench import create
from hw_nas_bench_api import HWNASBenchAPI as HWAPI

PATH_TO_NATS, PATH_TO_HW = ..., ... # paths to search-spaces files

nats = create(PATH_TO_NATS, searchspace="topology")
hw_api = HWAPI(PATH_TO_HW, search_space="nasbench201")

print(
    all([nats.get_net_config(index, dataset) == hw_api.get_net_config(index, dataset) \ 
        for index in range(n_nets) \
        for dataset in ["cifar10", "cifar100", "ImageNet16-120"] \
        ])
)# the ordering is the same iff this returns True
````

I would assume this is the case since many of the methods have the same name. However, I could not find any referring to `nats_bench`, hence my doubt!

**Comment by licj15** [comment]
Thank you for your interest in our work!
Yes, HW-NAS-Bench's order of the archs is same as NAS-Bench-201's order (https://github.com/D-X-Y/NAS-Bench-201/tree/6275241dd8cc25d39fa9618e4b9fa3ac2eda6d10). In other words, the two repos share the same "index" meaning.
